name: Build Report

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build_report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/latex
              with:
                  args: latexmk -pdf -interaction=batchmode -output-directory=build report.tex
            - uses: actions/upload-artifact@v2
              with:
                  name: Passive Radar Report
                  path: build/report.pdf
