name: Lint Report

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint_latex:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ChiefGokhlayeh/textidote-action@main
              with:
                  root_file: report.tex
            - uses: actions/upload-artifact@v2
              with:
                  name: textidote_report
                  path: report_textidote.html
